version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:      
      - echo installing dependencies for env $NODE_ENV...      
      - echo $NPM_TOKEN
      - npm install --registry=https://dev.verdaccio.chemcycled.in
  build:
    commands:
      - echo building project
      - npm run build:prod
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'
